encoder:
  kind: vit.masked_encoder
  patch_size: 16
  embedding_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  optim:
    kind: AdamW
    lr: 0.0003
    betas: [ 0.9, 0.95 ]
    weight_decay: 0.05
    schedule:
      kind: sequential
      schedules:
        - kind: linear
          max_epoch: 5
          mode: before_update
        - kind: cosine_annealing
          max_epoch: 95
          mode: before_update
decoder:
  kind: vit.masked_decoder
  patch_size: 16
  encoder_embedding_dim: 768
  decoder_embedding_dim: 512
  depth: 8
  num_heads: 16
  mlp_ratio: 4
  optim:
    kind: AdamW
    lr: 0.0003
    betas: [ 0.9, 0.95 ]
    weight_decay: 0.05
    schedule:
      kind: sequential
      schedules:
        - kind: linear
          max_epoch: 5
          mode: before_update
        - kind: cosine_annealing
          max_epoch: 95
          mode: before_update