kind: AdamW
lr: 0.0003
betas: [ 0.9, 0.95 ]
weight_decay: 0.05
schedule:
  kind: sequential
  schedules:
    - kind: linear
      max_epoch: 5
      mode: before_update
    - kind: cosine_annealing
      max_epoch: 95
      mode: before_update